services:
  - type: web
    name: hospital-back
    env: node
    buildCommand: npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5012